<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMeGGSV6\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMeGGSV6/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMeGGSV6.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMeGGSV6\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMeGGSV6\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MeGGSV6',
    'container.build_id' => '96aaa577',
    'container.build_time' => 1574159164,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMeGGSV6');
